### PR TITLE
feat: deploy with actions artifact

### LINKED ISSUE #71: Feature Request: GitHub Action Deployment
GitHub added a cool feature to deploy without needing to create a new branch for pages. [Reference](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site)

image

Would be cool to add support to this, if needed, I can help with it.

### PR DESCRIPTION
**Pull request by brenoepics**
image
closes #71

### CODE REVIEW

**Comment by brenoepics** [comment]
Also, `type`, `options` have been removed from the yml because they are not valid.

**Review by MathieuSoysal — COMMENTED** [review]
It's looks good to me, thank you and congratulation for this contribution 🥳

Do you have any source that proof the `type` and `options` are no longer used by Github Action ?

**Comment by brenoepics** [comment]
Hi, thanks.
the official docs does not mention these options for creating actions and the official VsCode/JetBrains WebStorm plugin warns that they are not part of the syntax in fact they [can be used in workflows](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-onworkflow_callinputs) but not in [action.yml](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_id)


I also took a look at some other actions and realized that they don't have this in the inputs, I was also looking at the [toolkit](https://github.com/actions/toolkit/tree/main/packages/core) because I'm working on a Java version of it and it treats all inputs as string and parse to see if it is a boolean, multiline, or string. 
composite actions like javadoc-publisher doesn't have parsing at all

**Review by MathieuSoysal — APPROVED** [review]

**Comment by MathieuSoysal** [comment]
Thank for your help and your answer 🔥

What do you think @pSub

**Pull request merged**
